LMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls'))
]

lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'
urlpatterns = [
    path('', views.index, name='index'),
    path('studentes/', views.Studentes.as_view(), name='studentes'),
    path('courses/', views.Courses.as_view(), name='courses'),
    path('graids/', views.Graids.as_view(), name='graids'),
    path('register/', views.register, name='register'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('student-cours-graid/', views.student_cours_graid, name='student_cours_graid'),
    path('new-student-cours-graid/', views.new_student_cours_graid, name='new_student_cours_graid'),
    path('edit-student-detail/<int:id>/', views.edit_student_detail, name='edit_student_detail')
]

lms/models.py
from django.db import models
from random import randint


class Student(models.Model):
    first_name = models.CharField(max_length=40, verbose_name='نام')
    last_name = models.CharField(max_length=40, verbose_name='نام خانوادگی')
    student_id = models.CharField(max_length=8, default='-', blank=True, verbose_name='شماره دانشجویی')
    courses = models.ManyToManyField('Course', through='StudentCourse')
    graduated = models.BooleanField(verbose_name='فارغ التحصیل', default=False)

    class Meta:
        verbose_name = "دانشجو"
        verbose_name_plural = "دانشجویان"

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_courses(self):
        return ' - '.join(self.courses.values_list('course_name', flat=True))

    get_courses.short_description = 'درس‌ها'

    def save(self, *args, **kwargs):
        self.student_id = randint(10**7, 10**8)
        super().save(*args, **kwargs)


class Course(models.Model):
    week = [
        ('Saturday', 'شنبه'),
        ('Sunday', 'یک شنبه'),
        ('Monday', 'دو شنبه'),
        ('Tuesday', 'سه شنبه'),
        ('Wednesday', 'چهار شنبه'),
        ('Thursday', 'پنج شنبه'),
        ('Friday', 'جمعه')
    ]
    course_name = models.CharField(max_length=40, verbose_name='نام درس')
    from_time = models.TimeField(verbose_name='از ساعت', null=True)
    to_time = models.TimeField(verbose_name='تا ساعت', null=True)
    day_of_week = models.CharField(verbose_name='روز هفته', max_length=10, choices=week, default=week[0][0])
    professor = models.ForeignKey('Professor', null=True, on_delete=models.SET_NULL, verbose_name='استاد')
    faculty = models.ForeignKey('Faculty', null=True, on_delete=models.CASCADE, verbose_name='دانشکده')
    room = models.ForeignKey('Room', null=True, on_delete=models.SET_NULL, verbose_name='اتاق')

    class Meta:
        verbose_name = "درس"
        verbose_name_plural = "دروس"

    def __str__(self):
        return self.course_name


class Professor(models.Model):
    first_name = models.CharField(max_length=40, verbose_name='نام')
    last_name = models.CharField(max_length=40, verbose_name='نام خانوادگی')
    email = models.EmailField(max_length=80, verbose_name='ایمیل')
    website = models.URLField(max_length=80, verbose_name='وب سایت')

    class Meta:
        verbose_name = "استاد"
        verbose_name_plural = "اساتید"

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def full_name(self):
        return self.__str__()

    full_name.short_description = 'نام و نام خانوادگی'

    def professor_courses(self):
        return ' - '.join(self.course_set.values_list('course_name', flat=True))

    professor_courses.short_description = 'دروس ارائه شده توسط استاد'


class Faculty(models.Model):
    name = models.CharField(max_length=40, verbose_name='دانشکده')

    class Meta:
        verbose_name = "دانشکده"
        verbose_name_plural = "دانشکده‌ها"

    def __str__(self):
        return 'دانشکده ' + self.name

    def faculty_courses(self):
        return ' - '.join(self.course_set.values_list('course_name', flat=True))

    faculty_courses.short_description = 'دروس ارائه شده در دانشکده'


class Room(models.Model):
    name = models.CharField(max_length=40, verbose_name='اتاق')
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, verbose_name='دانشکده')

    class Meta:
        verbose_name = "اتاق"
        verbose_name_plural = "اتاق‌ها"

    def __str__(self):
        return 'اتاق ' + self.name + ': ' + self.faculty.name

    def room_faculty(self):
        return self.faculty.name

    room_faculty.short_description = 'دانشکده'


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='نام دانشجو')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='نام درس')
    grade = models.FloatField(verbose_name='نمره درس')

    class Meta:
        verbose_name = "دانشجو-درس"
        verbose_name_plural = "دانشجویان-دروس"

    def __str__(self):
        return str(self.student) + ': ' + str(self.course) + ' = ' + str(self.grade)

lms/forms.py
from django import forms
from .models import StudentCourse, Student
from django.core.exceptions import ValidationError


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name']


class StudentCourseForm(forms.Form):
    first_name = forms.CharField(label='نام', max_length=40)
    last_name = forms.CharField(label='نام خانوداگی', max_length=40)
    course_name = forms.CharField(label='نام درس', max_length=40)
    grade = forms.FloatField(label="نمره", min_value=0.0, max_value=20.0)


class NewStudentCourseForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ['student', 'course', 'grade']


class NewStudentCourseForm_2(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ['course', 'grade']

    def clean_grade(self):
        grade = self.cleaned_data['grade']
        if grade < 0 or grade > 20:
            raise ValidationError("نمره نامناسب!")
        else:
            return grade


NewStudentCourseFormset = forms.formset_factory(NewStudentCourseForm_2, extra=4)

lms/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Count
from django.urls import reverse
from django.views import generic
from django.forms import formset_factory
from .models import Course, Student, StudentCourse
from .forms import StudentCourseForm, NewStudentCourseForm, NewStudentCourseFormset, StudentForm


def index(request):
    return render(request, 'lms/base_page.html')


# def studentes(request):
#     studentes = Student.objects.all()
#     return render(request, 'lms/studentes.html', {'studentes': studentes})

class Studentes(generic.ListView):
    template_name = 'lms/studentes.html'
    context_object_name = 'student_list'

    def get_queryset(self):
        return Student.objects.all()


# def courses(request):
#     student_num_per_course = StudentCourse.objects.values('course').annotate(num=Count('course')).values_list(
#         'course__course_name', 'num').order_by('course__course_name')
#     return render(request, 'lms/courses.html', {'student_num_per_course': student_num_per_course})

class Courses(generic.ListView):
    template_name = 'lms/courses.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        return StudentCourse.objects.values('course').annotate(num=Count('course')).values_list(
            'course__course_name', 'num').order_by('course__course_name')


# def student_course(request):
#     course_num = StudentCourse.objects.values('course').annotate(num=Count('course')).values_list(
#         'num', 'course__course_name').order_by('course__course_name')
#     student_course = StudentCourse.objects.values('course').values_list(
#         'course__course_name',
#         'student__first_name',
#         'student__last_name',
#         'grade'
#     ).order_by(
#         'course__course_name',
#         'student__first_name'
#     )
#     student_course_dict = {c_n[1]: [(x[1] + ' ' + x[2], x[3]) for x in student_course if x[0] == c_n[1]] for c_n in
#                            course_num}
#     return render(request, 'lms/student_course.html', {'student_course_dict': student_course_dict})


class Graids(generic.ListView):
    template_name = 'lms/student_course.html'
    context_object_name = 'graids'

    def get_queryset(self):
        course_num = StudentCourse.objects.values('course').annotate(num=Count('course')).values_list(
            'num', 'course__course_name').order_by('course__course_name')
        student_course = StudentCourse.objects.values('course').values_list(
            'course__course_name',
            'student__first_name',
            'student__last_name',
            'grade'
        ).order_by(
            'course__course_name',
            'student__first_name'
        )
        graids_dict = {c_n[1]: [(x[1] + ' ' + x[2], x[3]) for x in student_course if x[0] == c_n[1]] for c_n in
                       course_num}
        return graids_dict


# def register(request):
#     if request.method == 'GET':
#         return render(request, 'lms/register_form.html')
#     elif request.method == 'POST':
#         student = Student.objects.filter(first_name=request.POST['name'], last_name=request.POST['family'])
#         if not student:
#             student = Student.objects.create(first_name=request.POST['name'], last_name=request.POST['family'])
#         else:
#             student = student[0]
#         return HttpResponseRedirect(reverse('lms:detail', args=(student.id,)))


def register(request):
    if request.method == 'POST':
        student_form = StudentForm(request.POST)
        student_course_form_set = NewStudentCourseFormset(request.POST)

        if student_course_form_set.is_valid():
            tmp_set = set()
            for student_course_form in student_course_form_set:
                if student_course_form.cleaned_data.get("grade"):
                    if student_course_form.cleaned_data['course'] in tmp_set:
                        student_course_form.add_error(None, 'درس تکراری!')
                    else:
                        tmp_set.add(student_course_form.cleaned_data['course'])

        if student_form.is_valid() and student_course_form_set.is_valid():
            student = student_form.save()
            for student_course_form in student_course_form_set:
                if student_course_form.cleaned_data.get("grade"):
                    std_course_form = student_course_form.save(commit=False)
                    std_course_form.student = student
                    std_course_form.save()
                    student_course_form.save_m2m()
            return HttpResponseRedirect(reverse('lms:graids'))
    else:
        student_form = StudentForm()
        student_course_form_set = NewStudentCourseFormset()

    return render(request, 'lms/register_form.html',
                  {'student_form': student_form, 'formset': student_course_form_set})


class Detail(generic.DetailView):
    model = Student
    template_name = 'lms/detail.html'


def student_cours_graid(request):
    StudentCourseFormset = formset_factory(StudentCourseForm, extra=4)
    if request.method == 'POST':
        formset = StudentCourseFormset(request.POST, request.FILES)

        if formset.is_valid():

            for form in formset:
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                course_name = form.cleaned_data['course_name']
                grade = form.cleaned_data['grade']

                student = Student.objects.filter(first_name=first_name, last_name=last_name)
                course = Course.objects.filter(course_name=course_name)

                if not student:
                    student = Student.objects.create(first_name=first_name, last_name=last_name)
                else:
                    student = student[0]

                if not course:
                    course = Course.objects.create(course_name=course_name)
                else:
                    course = course[0]

                student_course = StudentCourse.objects.filter(student=student, course=course)
                if not student_course:
                    student_course = StudentCourse.objects.create(student=student, course=course, grade=grade)
                else:
                    student_course.update(grade=grade)

            return HttpResponseRedirect(reverse('lms:graids'))
    else:
        formset = StudentCourseFormset()

    return render(request, 'lms/student_cours_graid.html', {'formset': formset})


def new_student_cours_graid(request):
    if request.method == 'POST':
        form = NewStudentCourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('lms:graids'))
    else:
        form = NewStudentCourseForm()
    return render(request, 'lms/new_student_cours_graid.html', {'form': form})


def edit_student_detail(request, id):
    return render(request, 'lms/edit_student_detail.html', {'id': id})

lms/templates/lms/base_page.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lms/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'lms/css/base_page.css' %}">
    {% block style_page %}{% endblock %}
    <title>lms{% block title %}{% endblock %}</title>
</head>
<body class="w-75 mx-auto my-5">
<header>
    <h1 class="my-4">
        <a class="nav-link active text-dark" href="{% url 'lms:index' %}">
            سامانه آموزش دانش گستر
        </a>
    </h1>
    <nav class="nav">
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:register' %}">ثبت نام</a>
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:studentes' %}">دانشجویان</a>
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:courses' %}">درس ها</a>
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:student_cours_graid' %}">ثبت نمره</a>
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:new_student_cours_graid' %}">ثبت نمره جدید</a>
        <a class="btn btn-outline-primary mx-1" href="{% url 'lms:graids' %}">نمرات</a>
    </nav>
</header>
<hr/>
<main>
    <div class="mx-auto my-5">
        {% block main %}
        <h1 class="text-center">درخت تو گر بار دانش بگیرد</h1>
        <h1 class="text-center">به زیر آوری چرخ نیلوفری را</h1>
        {% endblock %}
    </div>
</main>
<footer class="footer">
    <hr/>
    <div class="container">
        <h5>
            &#169;
            کلیه حقوق این سایت متعلق به موسسه دانش گستر است.
        </h5>
    </div>
</footer>
</body>
</html>

lms/templates/lms/courses.html
{% extends "lms/base_page.html" %}

{% block title %} - درس ها{% endblock %}

{% block main %}
<table class="w-50 mx-auto table table-striped table-bordered text-center">
    <thead class="table-dark">
    <tr>
        <th> نام درس</th>
        <th> تعداد دانشجویان</th>
    </tr>
    </thead>
    <tbody>
    {% for x in course_list %}
    <tr>
        <td> {{ x.0 }} </td>
        <td> {{ x.1 }} </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

lms/templates/lms/detail.html
{% extends "lms/base_page.html" %}

{% block title %} - اطلاعات فردی {% endblock %}

{% block main %}

<div>
    <p class="text-center">نام و نام خانوادگی: {{ student }} </p>
    <p class="text-center">شماره دانشجویی: {{ student.student_id }} </p>
</div>

{% endblock %}

lms/templates/lms/edit_student_detail.html
{% extends "lms/base_page.html" %}

{% block title %} - اطلاعات فردی {% endblock %}

{% block main %}

<div>
    <p class="text-center"> {{ id }} </p>
</div>

{% endblock %}

lms/templates/lms/new_student_cours_graid.html
{% extends "lms/base_page.html" %}

{% block title %} - ثبت نمره {% endblock %}

{% block main %}

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

<form method="post" class="w-50 mx-auto my-5 text-center">
    {% csrf_token %}
    <table class="mx-auto">
        {{ form }}
        <tr>
            <td></td>
            <td><input class="btn btn-success" type="submit" value="ثبت اطلاعات"></td>
        </tr>
    </table>
</form>

{% endblock %}

lms/templates/lms/register_form.html
{% extends "lms/base_page.html" %}

{% block title %} - ثبت نام {% endblock %}

{% block main %}

<h3 class="text-center">«به سامانه ثبت نام دانش گستر خوش آمدید»</h3>

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

<form method="post" class="w-50 mx-auto my-5 text-center">
    {% csrf_token %}
    <table class="mx-auto">
        {{ student_form.as_table }}
        <tr><td><p> </p></td><td><p> </p></td></tr>
        {{ formset.as_table }}
        <tr>
            <td></td>
            <td><input class="btn btn-success" type="submit" value="ثبت اطلاعات"></td>
        </tr>
    </table>
</form>

{% endblock %}

lms/templates/lms/student_cours_graid.html
{% extends "lms/base_page.html" %}

{% block title %} - ثبت نمرات {% endblock %}

{% block main %}

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

<form method="post" class="w-50 mx-auto my-5 text-center">
    {% csrf_token %}
    {{ formset.management_form }}
    <table class="mx-auto">
        {% for form in formset %}
            {{ form }}
            <tr>
                <td><br></td>
                <td><br></td>
            </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td><input class="btn btn-success" type="submit" value="ثبت اطلاعات"></td>
        </tr>
    </table>
</form>

{% endblock %}

lms/templates/lms/student_course.html
{% extends "lms/base_page.html" %}

{% block title %} - نمرات {% endblock %}

{% block main %}
<table class="w-50 mx-auto table table-striped table-bordered text-center">
    <thead class="table-dark">
    <tr>
        <th> نام درس</th>
        <th>دانشجو</th>
        <th>نمره</th>
    </tr>
    </thead>
    <tbody>
    {% for key, value in graids.items %}
    {% for x in value %}
        <tr>
            {% if forloop.first %}
            <td rowspan="{{ value|length }}"> {{ key }} </td>
            {% endif %}
            {% if x.1 < 10 %}
            <td class="text-danger"> {{ x.0 }} </td>
            <td class="text-danger"> {{ x.1 }} </td>
            {% else %}
            <td> {{ x.0 }} </td>
            <td> {{ x.1 }} </td>
            {% endif %}
        </tr>
    {% endfor %}
    {% endfor %}
    </tbody>
</table>
{% endblock %}

lms/templates/lms/studentes.html
{% extends "lms/base_page.html" %}

{% block title %} - دانشجویان{% endblock %}

{% block main %}
<table class="w-50 mx-auto table table-striped table-bordered text-center">
    <thead class="table-dark">
    <tr>
        <th> نام و نام خانوادگی</th>
        <th> شماره دانشجویی</th>
        <th> ویرایش اطلاعات</th>
    </tr>
    </thead>
    <tbody>
    {% for student in student_list %}
    <tr>
        <td> <a class="text-success" href="{% url 'lms:detail' student.id %}"> {{ student }} </a> </td>
        {% if student.student_id %}
        <td> {{ student.student_id }}</td>
        {% else %}
        <td> - </td>
        {% endif %}
        <td> <a class="text-success" href="{% url 'lms:edit_student_detail' student.id %}"> ویرایش اطلاعات </a> </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}